version: "3"
networks:
  expense:
volumes:
  mysql-data: #docker volume create mysql
services:
  mysql:
    image: hari6244/mysql:v1
    container_name: mysql-container #--name mysql-container
    volumes:
    - mysql-data:/var/lib/mysql #-v mysql-data:/var/lib/mysql
  backend:
    image: hari6244/backend:v1
    container_name: backend-container
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on: 
    - mysql
  frontend:
    image: hari6244/frontend:v1
    container_name: frontend-container
    ports:
    - 80:80 #host-port:container-port, It can be 8080:80 also. You can give any host port here.
    depends_on: 
    - backend