version: "3"
networks:
  expense:
volumes:
  mysql: #docker volume create mysql
services:
  mysql:
    image: joindevops/mysql:v1
    containerName: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: joindevops/backend:v1
    containerName: backend
    depends_on: 
    - mysql
  frontend:
    image: joindevops/frontend:v1
    containerName: frontend
    ports:
    - 80:80
    depends_on: 
    - backend

