FROM 20.19.1-alpine3.21
EXPOSE 80
RUN mkdir /opt/server
WORKDIR /opt/server
COPY package.json .
COPY *.js .
RUN npm install
CMD ["node","index.js"]
#ENV DB_HOST="mysql"
ENV DB_HOST="mysql"



# FROM node:20
# EXPOSE 80
# RUN mkdir /opt/server
# WORKDIR /opt/server
# COPY package.json .
# COPY *.js .
# RUN npm install
# CMD ["node","index.js"]
# #ENV DB_HOST="mysql"
# ENV DB_HOST="mysql"